# travis-ci config file for rpn_service

notifications:
  email:
    recipients:
      - davenicolette@gmail.com
    on_success: change
    on_failure: change

language: ruby
rvm:
  - 2.2.2

branches:
  only: master

install:
  - bundle install

script:
  - ruby rpn_service.rb &
  - rake
  - kill `cat rpn_service.pid`

